---
Profiles:
  HealthcareOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      HealthcareConsortium:
        Organizations:
        - *InsuranceOrg
        - *HospitalOrg

  HealthcareChannel:
    Consortium: HealthcareConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *InsuranceOrg
      - *HospitalOrg

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: crypto-config/peers/ordererOrganizations/orderer-org/msp
- &InsuranceOrg
  Name: InsuranceOrgMSP
  ID: InsuranceOrgMSP
  MSPDir: crypto-config/peers/peerOrganizations/insurance-org/msp
  AnchorPeers:
  - Host: insurance-peer
    Port: 7051
- &HospitalOrg
  Name: HospitalOrgMSP
  ID: HospitalOrgMSP
  MSPDir: crypto-config/peers/peerOrganizations/hospital-org/msp
  AnchorPeers:
  - Host: hospital-peer
    Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:
